services:
  web:
    container_name: backend_potential_pancake
    image: potential_pancake_backend/seniores
    build: .
    tty: true
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev